port=8000
db.type=mysql
db.table=patient_records

# MySQL config
db.host=localhost
db.port=3306
db.name=hospital
db.user=root
db.pass=

# mTLS (set to false for testing without certs)
mtls.enabled=false
mtls.keystore=certs/server.p12
mtls.truststore=certs/truststore.p12
mtls.password=password

# Supabase config (uncomment to use)
#supabase.url=https://xvlilgsawbqpedmrbdkv.supabase.co
#supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2bGlsZ3Nhd2JxcGVkbXJiZGt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgxMjExMDYsImV4cCI6MjA4MzY5NzEwNn0.6_k63XlmfDIJ2jN0txMjcY-SKwYH7H_HF4b-3NrDKbA
#db.schema=public