port=8000
db.type=supabase
db.table=patient_records

# mTLS
mtls.enabled=true
mtls.keystore=certs/server.p12
mtls.truststore=certs/truststore.p12
mtls.password=password

supabase.url=https://xvlilgsawbqpedmrbdkv.supabase.co
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2bGlsZ3Nhd2JxcGVkbXJiZGt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgxMjExMDYsImV4cCI6MjA4MzY5NzEwNn0.6_k63XlmfDIJ2jN0txMjcY-SKwYH7H_HF4b-3NrDKbA
db.schema=public